Model:
  _target_: semiafa.Model
  num_years: 5
  # property values from Optuna sweeper run over 200 cycles
  air_heat_lag: 0
  air_melt_multiplier: 0.2
  ice_power: 0.9
  ice_freeze_multiplier: 8.3
  sun_melt_multiplier: 19.6
  ocean_heat_melt_multiplier: 0.2
  #
  lat_for_insolation_calc: 75 # representative latitude for approximate insolation
  max_sie: 0.99999
  min_sie: 0.00001
  insolation_year: 2010
  insolation_file: data/insolation.pkl # .pkl file for caching insolation data
  start_year: 2006 # 2014
  wind_spread_start: 136 #  - first of each month J:1, F:32, M:60, A:91, M:121 
  wind_spread_stop: 156 # ~ 50,000 km2 by day 150, but highly variable
  wind_spread_rate: 0.0001 # proportion of ice area exposed by wind daily, 5000km2 is ~0.00033
  shade_on: No
  shade_start: 137
  shade_stop: 201
  shade_area: 0.001  # total area of ice cap approx 15,000,000 km2, shading 2000km2 is 0.000133r, 
Maisie:
  _target_: maisie.SeaIceRecord
  csv_file_path: maisie-data/2023-06-01/masie_4km_allyears_extent_sqkm.csv
  regions: [' (1) Beaufort_Sea',' (2) Chukchi_Sea',' (3) East_Siberian_Sea',' (4) Laptev_Sea',' (5) Kara_Sea',' (6) Barents_Sea',' (11) Central_Arctic']
